import { mkdir, readFile, writeFile } from "node:fs/promises";
import { findExample } from "@counterexample-studio/examples";
import { runRuntimeWorker } from "../packages/cli/src/runtime-client.js";

// This artifact is an actual saved result. It has no browser execution backend.
const example = findExample("chunk-buggy");
const report = await runRuntimeWorker({ modulePath: example.modulePath, propertiesPath: example.propertiesPath, seed: example.defaultSeed, numRuns: example.defaultRuns });
const entry = report.cases[0]!;
if (entry.status !== "fail" || !entry.failingInput || !entry.expected || !entry.actual) throw new Error("The demo requires a real failing chunk report.");
const css = await readFile(new URL("../packages/web/src/styles.css", import.meta.url), "utf8");
const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const codeFrame = (label: string, value: string, failure = false) => `<div class="code-frame ${failure ? "code-fail" : ""}"><div class="code-heading"><strong>${escape(label)}</strong></div><pre>${escape(value)}</pre></div>`;
const metric = (label: string, value: string) => `<div><dt>${escape(label)}</dt><dd>${escape(value)}</dd></div>`;
const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Inspect a real, reproducible property-test failure from Property Check. A saved local-engine report with a minimal witness and shrink trace."><title>Property Check · saved report</title><style>${css}
.demo-sidebar p { margin-top: 12px; font-size: 13px; color: var(--muted); } .demo-sidebar h2 { font-size: 17px; } .demo-sidebar pre { font-size: 11px; margin: 16px 0; } .demo-sidebar .button { margin-top: 20px; text-decoration: none; width: 100%; } .demo-label { font-size: 12px; color: var(--muted); } .topbar .button, .report-heading .button { text-decoration: none; } .demo-source { margin-top: 28px; padding-top: 20px; border-top: 1px solid var(--line); } .demo-source p { color: var(--muted); margin-top: 8px; font-size: 12px; } @media(max-width:800px) { .demo-sidebar { display: none; } .workspace { grid-template-columns: 1fr; } }
</style></head><body><header class="topbar"><a class="brand" href="https://github.com/dicnunz/property-check"><span class="brand-mark" aria-hidden="true">δ</span><span>Property Check</span></a><a class="button" href="https://github.com/dicnunz/property-check">View source</a></header>
<div class="workspace"><aside class="sidebar demo-sidebar"><h2>Chunk · saved run</h2><p>The chunk function drops the final partial chunk. The property engine found the failing input below and shrank it to one value.</p><div class="sidebar-footnote"><h2>Run it locally</h2><pre>npm install\nnpm run build\nnpm run studio -- ui --open</pre><p>Pure synchronous JS / TS. The CLI and browser share one deterministic, local engine.</p><a class="button" href="https://github.com/dicnunz/property-check#run">Run locally</a></div></aside>
<main class="main-column"><p class="notice-banner">Saved report. Run and replay tests in the local app.</p><article class="report-surface"><div class="report-heading"><div><div class="title-line"><h1>${escape(entry.label)}</h1><span class="status status-fail">Failed</span></div><p class="report-subtitle">Counterexample found.</p><p class="report-origin">Generated ${escape(report.generatedAt)} · Chunk (buggy)</p></div><a class="button" href="report.json" download>Download JSON</a></div>
<dl class="metrics">${metric("Seed", String(entry.seed))}${metric("Runs before failure", String(entry.numRuns))}${metric("Accepted shrinks", String(entry.numShrinks))}${metric("Shrink path", entry.counterexamplePath ?? "Unavailable")}</dl><div class="suite-strip"><p><strong>1 property</strong><span>0 passed · 1 failed</span></p><span>${escape(report.title)}</span></div>
<section><h2>Counterexample</h2><p class="invariant"><code>${escape(entry.invariant)}</code></p><div class="evidence-grid">${codeFrame("Failing input", entry.failingInput.preview)}${codeFrame("Expected", entry.expected.value.preview)}${codeFrame("Actual", entry.actual.value.preview, true)}</div></section>
<section class="replay-section"><div class="section-heading"><div><h2>Reproduce this failure</h2><p>From the repository root after building, run this command in your terminal.</p></div></div><div class="copyable"><pre>${escape(entry.rerunCommand)}</pre></div></section>
<section class="details-section"><h2>Accepted shrink path</h2><p class="detail-caption">Recorded failing candidates in execution order. The final row is the minimal witness.</p><div class="table-scroll"><table><thead><tr><th>Step</th><th>Description</th><th>Input</th><th>Actual</th></tr></thead><tbody>${entry.shrinkTrace.map((step, index) => `<tr><td>${index + 1}</td><td>${escape(step.label)}</td><td><code>${escape(step.input.preview.replace(/\s+/g, " "))}</code></td><td><code>${escape(step.actual.value.preview.replace(/\s+/g, " "))}</code></td></tr>`).join("")}</tbody></table></div></section>
<section class="demo-source"><h2>Try the complete workbench</h2><p>Import this report in the local app to replay the failure.</p><p><a href="https://github.com/dicnunz/property-check#run">Install Property Check</a> · <a href="report.json" download>Get this report</a></p></section></article></main></div></body></html>`;
await mkdir(new URL("../demo/", import.meta.url), { recursive: true });
await writeFile(new URL("../demo/report.json", import.meta.url), `${JSON.stringify(report, null, 2)}\n`);
await writeFile(new URL("../demo/index.html", import.meta.url), html);
console.log(`Generated demo/index.html from ${entry.id}: seed=${entry.seed} path=${entry.counterexamplePath}`);
